client.credentials.file: src/main/resources/ebay-config.yaml
environment: PRODUCTION
endpoint: https://event-notif-java-sdk-heroku.herokuapp.com/webhook
verificationToken: 71745723-d031-455c-bfa5-f90d11b4f20a
