name: ebay-config

# UPDATE the values in this file for the appropriate environment. Required to fetch PublicKey for integrity check.
api.sandbox.ebay.com:
  appid:
  certid:
  devid:
  redirecturi:

api.ebay.com:
  appid:
  certid:
  devid:
  redirecturi:
